## Numpy

In [1]:
import numpy as np

In [2]:
# Create an array of 3 lists
jeff_salary = [2000,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300, 2500, 2500]
base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2000 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]

In [3]:
# Create an array of 3 bonus lists
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])
print(bonus)

[[500 400 400]
 [600 300 400]
 [200 500 400]]

## Performing Element-wise operations

In [4]:
# Create a new array by adding the base_salary and bonus arrays
salary_bonus = base_salary+bonus
print(salary_bonus)

[[2500 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]

## using Numpy Statistical Functions

In [5]:
# Find the maximum values in the array
print(salary_bonus.max())

3400

In [6]:
# Create an array containing the maximum value in each row
print(np.amax(salary_bonus, axis=1))

[3400 3200 3000]

In [7]:
# Create an array containing the maximum value in each column
print(np.amax(salary_bonus, axis=0))

[3200 3400 3400]

## Pandas

In [8]:
# Create a series of the list
import pandas as pd
data = ['Jeff Russell','Jane Boorman','Tom Heints']
emps_names = pd.Series(data)
print(emps_names)

0    Jeff Russell
1    Jane Boorman
2      Tom Heints
dtype: object

In [9]:
# Create a series of the list and rename the index values
data = ['Jeff Russell','Jane Boorman','Tom Heints']
emps_names = pd.Series(data, index=[9001,9002,9003])
print(emps_names)

9001    Jeff Russell
9002    Jane Boorman
9003      Tom Heints
dtype: object

## Accessing data in a series

In [10]:
# Print the employee name in index 9001
print(emps_names[9001])

# Print the employee name in the index location 0
print(emps_names.iloc[0])

# Print the employee names in the index locations 9001 to 9002
print(emps_names.loc[9001:9002])

# Print the employees names in the indexa location 0 to 1
print(emps_names.iloc[0:2])

# Print the employees names in the indexa location 0 to 1
print(emps_names[0:2])

Jeff Russell
Jeff Russell
9001    Jeff Russell
9002    Jane Boorman
dtype: object
9001    Jeff Russell
9002    Jane Boorman
dtype: object
9001    Jeff Russell
9002    Jane Boorman
dtype: object

## Combining series into a dataframe

In [11]:
# Create list of employee emails and create a Series with column name 'emails'
data = ['Jeff.Russell','Jane.Boorman','Tom.Heints']
emps_emails = pd.Series(data, index=[9001,9002,9003], name='emails')

# Change the emps_names column name to 'names
emps_names.name = 'names'

# Create a dataframe of the concatenation of the 2 series
df = pd.concat([emps_names, emps_emails], axis=1)
print(df)

             names        emails
9001  Jeff Russell  Jeff.Russell
9002  Jane Boorman  Jane.Boorman
9003    Tom Heints    Tom.Heints

## Creating pandas dataframes

## YFinance module

In [12]:
import yfinance as yf

# Load 5 days of the TSLA ticker
tkr = yf.Ticker('TSLA')
hist = tkr.history(period="5d")

# Drop the Dividends and Stock Splits columns
hist = hist.drop(["Dividends","Stock Splits"], axis=1)

# CHange the index name to Date
hist = hist.reset_index().set_index('Date')
hist

,Open,High,Low,Close,Volume
Date,,,,,
2025-06-06 00:00:00-04:00,298.829987,305.500000,291.140015,295.140015,164747700
2025-06-09 00:00:00-04:00,285.959991,309.829987,281.850006,308.579987,140908900
2025-06-10 00:00:00-04:00,314.940002,327.829987,310.670013,326.089996,151256500
2025-06-11 00:00:00-04:00,334.399994,335.500000,322.500000,326.429993,121851400
2025-06-12 00:00:00-04:00,323.075012,332.549988,319.100006,319.600189,79447599

## Json Module

In [13]:
import json
import pandas as pd

# Create a data dictionary in the shape of a json file
data = [
    {"Empno":9001, "Salary":3000},
    {"Empno":9002, "Salary":2800},
    {"Empno":9003, "Salary":2500}
]

# Save the dictionary as a json file
json_data = json.dumps(data)

# Read the json file into the salary dataframe
salary = pd.read_json(json_data)

# Rename the index 'Empno'
salary = salary.set_index('Empno')
print(salary)

       Salary
Empno
9001     3000
9002     2800
9003     2500

C:\Users\timry\AppData\Local\Temp\ipykernel_4236\2768000728.py:15: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  salary = pd.read_json(json_data)

In [14]:
import pandas as pd

# Create a list of employee information
data = [['9001','Jeff Russell','sales'],
        ['9002','Jane Boorman','sales'],
        ['9003','Tom Heints','sales']]

# Create a dataframe from the data lsit
emps = pd.DataFrame(data,columns = ['Empno','Name','Job'])
column_types = {'Empno':int, 'Name':str, 'Job':str}
emps = emps.astype(column_types)
emps = emps.set_index('Empno')
print(emps)

               Name    Job
Empno
9001   Jeff Russell  sales
9002   Jane Boorman  sales
9003     Tom Heints  sales

## Combining Dataframes

In [15]:
# Join the emps and salary dataframes
emps_salary = emps.join(salary)
print(emps_salary)

               Name    Job  Salary
Empno
9001   Jeff Russell  sales    3000
9002   Jane Boorman  sales    2800
9003     Tom Heints  sales    2500

In [16]:
# Create new series 
new_emp = pd.Series({'Name': 'John Hardy', 'Job': 'sales'}, name = 9004)

# Append the series to the emps dataframe using the name value as the index 
emps.loc[new_emp.name] = new_emp
print(emps)

               Name    Job
Empno
9001   Jeff Russell  sales
9002   Jane Boorman  sales
9003     Tom Heints  sales
9004     John Hardy  sales

In [17]:
# Join the emps and salary dataframes
emps_salary = emps.join(salary)
print(emps_salary)

               Name    Job  Salary
Empno
9001   Jeff Russell  sales  3000.0
9002   Jane Boorman  sales  2800.0
9003     Tom Heints  sales  2500.0
9004     John Hardy  sales     NaN

In [18]:
# Perform an inner join on the emps and salary dataframes
emps_salary = emps.join(salary, how = 'inner')
print(emps_salary)

               Name    Job  Salary
Empno
9001   Jeff Russell  sales    3000
9002   Jane Boorman  sales    2800
9003     Tom Heints  sales    2500

# One-to-many joins

In [19]:
# Create order dataframe using the data list
data = [[2608,9001,35],
        [2617,9001,35],
        [2620,9001,139],
        [2621,9002,95],
        [2626,9002,218]]
orders = pd.DataFrame(data, columns=['Pono','Empno','Total'])
print(orders)

   Pono  Empno  Total
0  2608   9001     35
1  2617   9001     35
2  2620   9001    139
3  2621   9002     95
4  2626   9002    218

In [20]:
# Merge the emps dataframe with the orders as a inner join on Empno fields
emp_orders = emps.merge(orders, 
                        how="inner", 
                        left_on="Empno",
                        right_on="Empno").set_index("Pono")
print(emp_orders)

      Empno          Name    Job  Total
Pono
2608   9001  Jeff Russell  sales     35
2617   9001  Jeff Russell  sales     35
2620   9001  Jeff Russell  sales    139
2621   9002  Jane Boorman  sales     95
2626   9002  Jane Boorman  sales    218

In [21]:
# Get the mean of the Empno group
print(orders.groupby(['Empno'])["Total"].mean())

Empno
9001     69.666667
9002    156.500000
Name: Total, dtype: float64

In [22]:
# Get the sum of the Emppno group
(orders.groupby(['Empno'])["Total"].sum())

Empno
9001    209
9002    313
Name: Total, dtype: int64

# Loading the sample dataset into a panda dataframe

In [23]:
# Load the csv file and set the columns to 'review' and 'sentiment'
# use tab as the delimiter
df = pd.read_csv('amazon_cells_labelled.txt', names=['review', 'sentiment'], sep='\t')

In [24]:
# Display the first 3 rows
df.head(3)

                                              review  sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1

# Splitting the sample dataset into training set and a test set

In [25]:
from sklearn.model_selection import train_test_split

# Create the review (X) and sentiments (y) arrays
reviews = df['review'].values
sentiments = df['sentiment'].values

# Split the data into train and test arrays
reviews_train, reviews_test, sentiment_train, sentiment_test = train_test_split(reviews, 
                                                                                sentiments, 
                                                                                test_size=0.2, 
                                                                                random_state=500)

## Transforming text into numerical feature vectors

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate a CountVectorizer, fit the reviews(X) and transfor the ttrain and test data
vectorizer = CountVectorizer()
vectorizer.fit(reviews)
X_train = vectorizer.transform(reviews_train)
X_test = vectorizer.transform(reviews_test)

## Train and Evaluate the Model

In [27]:
from sklearn.linear_model import LogisticRegression

# Create the LogisticRegression model
classifier = LogisticRegression()
classifier.fit(X_train, sentiment_train)

LogisticRegression()

In [28]:
# Retrieve the accuracy score from the model
accuracy = classifier.score(X_test, sentiment_test)
print("Accuracy:", accuracy)

Accuracy: 0.81

## Making predictions on new data

In [29]:
# Predict the sentiment of the 3 phrases using the classifier model
new_reviews = ['Old version of python useless', 'Very good effort', 'Clear and concise']
X_new = vectorizer.transform(new_reviews)
print(classifier.predict(X_new))

[0 1 1]