## Data to Aggregate

In [1]:
import pandas as pd

In [2]:
# Create an orders list
orders = [
 (9423517, '2021-08-04', 9001),
 (4626232, '2021-08-04', 9003),
 (9423534, '2021-08-04', 9001),
 (9423679, '2021-08-05', 9002),
 (4626377, '2021-08-05', 9003),
 (4626412, '2021-08-05', 9004),
 (9423783, '2021-08-06', 9002),
 (4626490, '2021-08-06', 9004)
]

# Create a dataframe based on the orders list
df_orders = pd.DataFrame(orders, columns=['OrderNo','Date','Empno'])

In [3]:
# Create an order details list
details = [
 (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, 'Socks', 'DC', 10.0, 2),
 (9423534, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, 'Hoody', 'Animal', 44.0, 1),
 (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, 'Shorts', 'Globe', 26.0, 1),
 (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, 'Sweater', 'Dickies', 56.0, 1)
]

# Create a dataframe based on the order details list
df_details = pd.DataFrame(details, columns=['OrderNo','Item','Brand','Price','Quantity'])

In [4]:
# Create an employee lsit
emps = [
 (9001, 'Jeff Russell', 'LA'),
 (9002, 'Nick Boorman', 'San Francisco'),
 (9003, 'Tom Heints', 'NYC'),
 (9004, 'Maya Silver', 'Philadelphia')
]

# Create a dataframe based on the employee list
df_emps = pd.DataFrame(emps, columns=['Empno','Empname','Location'])

In [5]:
# Create a location list
locations = [
 ('LA', 'West'),
 ('San Francisco', 'West'),
 ('NYC', 'East'),
 ('Philadelphia', 'East')
]

# Create a dataframe based on the location list
df_location = pd.DataFrame(locations, columns=['Location','Region'])

## Combining Dataframes

In [6]:
# Merge the df_orders and df_details lists
df_sales = df_orders.merge(df_details, how='inner', on='OrderNo')
df_sales.head(3)

   OrderNo        Date  Empno    Item           Brand  Price  Quantity
0  9423517  2021-08-04   9001   Jeans        Rip Curl   87.0         1
1  9423517  2021-08-04   9001  Jacket  The North Face  112.0         1
2  4626232  2021-08-04   9003   Socks            Vans   15.0         1

In [7]:
# Add 'Totak' feature to the df_sales datgaframe
df_sales['Total'] = df_sales['Price']*df_sales['Quantity']
df_sales.head(3)

   OrderNo        Date  Empno    Item           Brand  Price  Quantity  Total
0  9423517  2021-08-04   9001   Jeans        Rip Curl   87.0         1   87.0
1  9423517  2021-08-04   9001  Jacket  The North Face  112.0         1  112.0
2  4626232  2021-08-04   9003   Socks            Vans   15.0         1   15.0

In [8]:
# Override df_sales with 3 columns
df_sales = df_sales[['Date','Empno','Total']]
df_sales.head(3)

         Date  Empno  Total
0  2021-08-04   9001   87.0
1  2021-08-04   9001  112.0
2  2021-08-04   9003   15.0

In [9]:
# Merge df_sales with df_emps
df_sales_emps = df_sales.merge(df_emps, how='inner', on='Empno')
df_sales_emps.head(3)

         Date  Empno  Total       Empname Location
0  2021-08-04   9001   87.0  Jeff Russell       LA
1  2021-08-04   9001  112.0  Jeff Russell       LA
2  2021-08-04   9003   15.0    Tom Heints      NYC

In [10]:
# Merge df_sales_emps with dF_locations
df_result = df_sales_emps.merge(df_location, how='inner', on='Location')
df_result.head(3)

         Date  Empno  Total       Empname Location Region
0  2021-08-04   9001   87.0  Jeff Russell       LA   West
1  2021-08-04   9001  112.0  Jeff Russell       LA   West
2  2021-08-04   9003   15.0    Tom Heints      NYC   East

In [11]:
# Override df_result with only 3 columns
df_result = df_result[['Date','Region','Total']]
df_result.head(3)

         Date Region  Total
0  2021-08-04   West   87.0
1  2021-08-04   West  112.0
2  2021-08-04   East   15.0

## Grouping and aggregating the data

In [12]:
# Calculate the sum of the grouping Date and Region
df_date_region = df_result.groupby(['Date','Region']).sum()
df_date_region

                   Total
Date       Region
2021-08-04 East     97.0
           West    243.0
2021-08-05 East    160.0
           West     35.0
2021-08-06 East    110.0
           West     86.0

## Viewing Specific Aggregations by Multiindex

In [13]:
# View the multiindex dataframe created by the groupby function
print(df_date_region.index)

MultiIndex([('2021-08-04', 'East'),
            ('2021-08-04', 'West'),
            ('2021-08-05', 'East'),
            ('2021-08-05', 'West'),
            ('2021-08-06', 'East'),
            ('2021-08-06', 'West')],
           names=['Date', 'Region'])

In [14]:
# Get the datatype of the df_rate_region groupby
type(df_date_region)

pandas.core.frame.DataFrame

In [15]:
# Filter for the index date and region
df_date_region[df_date_region.index.isin([('2021-08-05','West')])]

                   Total
Date       Region
2021-08-05 West     35.0

In [16]:
# Filter for the 2 indexes of date and region
df_date_region[df_date_region.index.isin([('2021-08-05','West'),('2021-08-05','East')])]

                   Total
Date       Region
2021-08-05 East    160.0
           West     35.0

## Slicing a range of aggregated values

In [17]:
# Slice the indexes for the 2 dates and 2 regions
# If the region is the same, the first date will pull all rows for that date starting with the region
# The second date will pull all regions until the region listed
df_date_region[('2021-08-04','East'):('2021-08-05','West')]

                   Total
Date       Region
2021-08-04 East     97.0
           West    243.0
2021-08-05 East    160.0
           West     35.0

In [18]:
# Slice the indexes for the 2 dates
# This will include all regions not like the slice above
df_date_region[('2021-08-04'):('2021-08-05')]

                   Total
Date       Region
2021-08-04 East     97.0
           West    243.0
2021-08-05 East    160.0
           West     35.0

## Slicing within aggregation levels

In [19]:
# Slice based on the index location names
# The first slice is based on the date
# The second slice is based on the Region
# 'None' is used to include all the values of the region
df_date_region.loc[(slice('2021-08-04','2021-08-05'),slice(None)),:]

                   Total
Date       Region
2021-08-04 East     97.0
           West    243.0
2021-08-05 East    160.0
           West     35.0

In [20]:
# Slice based on the index location names
# The first slice is based on the date
# The second slice is based on the Region
df_date_region.loc[(slice('2021-08-04','2021-08-05'),slice('East')),:]

                   Total
Date       Region
2021-08-04 East     97.0
2021-08-05 East    160.0

## Adding a grand total

In [21]:
# Create series containing a total value for the df_date_region dataframe 
ps = pd.Series(df_date_region.sum(axis = 0))
print(ps)

Total    731.0
dtype: float64

In [22]:
# Rewrote this section myself

# Add the name 'All' to the date component of the index and the region component of the index
ps.name=('All','All')

# Create a dataframe from the Series and transpose it to become a row
ps = pd.DataFrame(ps).T

# Create a new total dataframe by concatenating the df_date_region and the ps (total) 
df_date_region_total = pd.concat([df_date_region, ps])

# Display the dataframe
df_date_region_total

                 Total
2021-08-04 East   97.0
           West  243.0
2021-08-05 East  160.0
           West   35.0
2021-08-06 East  110.0
           West   86.0
All        All   731.0

In [23]:
# Retrieve the grand total row
df_date_region_total[df_date_region_total.index.isin([('All','All')])]

         Total
All All  731.0

## Adding Subtotals

In [24]:
# Rewrote the book code because it did not work with deprecated append functions
df_totals = pd.DataFrame()
df_totals2 = pd.DataFrame()

for date, date_df in df_date_region_total.groupby(level=0):
    # Check to see if the date value is the 'All' grand total row
    if date != 'All':
        ps = date_df.sum(axis = 0) # Sum the date totals
        ps.name=(date,'All') # Add the names for date and 'All'
        ps = pd.DataFrame(ps).T # Create a dataframe from the Series and transpose it to become a row
    else: ps = None # Set the ps variable to null if the date value is 'All'

    # Set the df_totals dataframe to the concatenated dataframes date_df and ps
    df_totals = pd.concat([date_df, ps])

    # Append the df_totals dataframe to the df_totals2 dataframe
    df_totals2 = pd.concat([df_totals2, df_totals])

In [25]:
# Display the df_totals dataframe
df_totals2

                 Total
2021-08-04 East   97.0
           West  243.0
           All   340.0
2021-08-05 East  160.0
           West   35.0
           All   195.0
2021-08-06 East  110.0
           West   86.0
           All   196.0
All        All   731.0

## Selecting all rows in a group

In [26]:
# This provides all detail rows associated with a grouping row
group = df_result.groupby(['Date','Region'])
group.get_group(('2021-08-05','East'))

         Date Region  Total
7  2021-08-05   East   44.0
8  2021-08-05   East   38.0
9  2021-08-05   East   78.0