## Combining lists and tuples with +

In [1]:
# Create 3 tuples then combine them using '+'
orders_2021_08_04 = [
 (9423517, '2021-08-04', 9001),
 (4626232, '2021-08-04', 9003),
 (9423534, '2021-08-04', 9001)
]
orders_2021_08_05 = [
 (9423679, '2021-08-05', 9002),
 (4626377, '2021-08-05', 9003),
 (4626412, '2021-08-05', 9004)
]
orders_2021_08_06 = [
 (9423783, '2021-08-06', 9002),
 (4626490, '2021-08-06', 9004)
]

orders = orders_2021_08_04 + orders_2021_08_05 + orders_2021_08_06

orders

[(9423517, '2021-08-04', 9001),
 (4626232, '2021-08-04', 9003),
 (9423534, '2021-08-04', 9001),
 (9423679, '2021-08-05', 9002),
 (4626377, '2021-08-05', 9003),
 (4626412, '2021-08-05', 9004),
 (9423783, '2021-08-06', 9002),
 (4626490, '2021-08-06', 9004)]

## Combining Dictionaries with **

In [2]:
# Create a dictionary of shipping address
extrafields_9423517 = {
    'ShippingInstructions' : { 'name' : 'John Silver',
                               'Phone': [{'type':'Office', 'number':'809-123-9309'},
                                         {'type':'Mobile', 'number':'417-123-4567'}]}
}

# Create a dictionary of an order
order_9423517 = {'OrderNo':9423517, 'Date':'2022-02-04', 'Empno':9001}

# Combine the 2 dictionaries
order_9423517 = {**order_9423517, **extrafields_9423517}

# Display the order
order_9423517

{'OrderNo': 9423517,
 'Date': '2022-02-04',
 'Empno': 9001,
 'ShippingInstructions': {'name': 'John Silver',
  'Phone': [{'type': 'Office', 'number': '809-123-9309'},
   {'type': 'Mobile', 'number': '417-123-4567'}]}}

## Combining Corresponding Rows to Two Structures

In [3]:
# Create order details list
details = [
 (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, 'Socks', 'DC', 10.0, 2),
 (9423534, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, 'Hoody', 'Animal', 44.0, 1),
 (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, 'Shorts', 'Globe', 26.0, 1),
 (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, 'Sweater', 'Dickies', 56.0, 1)
]

In [4]:
# Create 2 orders in one list and the details in another list
orders2 = [
 (9423517, '2021-08-04', 9001),
 (4626232, '2021-08-04', 9003)]
details2 = [
 (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1)]

# Combine the 2 orders with the details using an outer list comprehension
order_details2 = []
for o in orders2:
    for d in details2:
        if d[0] == o[0]:
            order_details2.append(o + d[1:])

# Diplay the 2 orders
order_details2

[(9423517, '2021-08-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2021-08-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2021-08-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2021-08-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1)]

In [5]:
# Conbines the order detail and order summary using an inner list comprehension
order_details2 = [[o for o in orders if d[0] == o[0]][0] + d[1:] for d in details]
order_details2

[(9423517, '2021-08-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2021-08-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2021-08-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2021-08-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, '2021-08-04', 9001, 'Socks', 'DC', 10.0, 2),
 (9423534, '2021-08-04', 9001, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, '2021-08-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, '2021-08-05', 9003, 'Hoody', 'Animal', 44.0, 1),
 (4626377, '2021-08-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, '2021-08-05', 9004, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, '2021-08-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, '2021-08-06', 9002, 'Shorts', 'Globe', 26.0, 1),
 (4626490, '2021-08-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, '2021-08-06', 9004, 'Sweater', 'Dickies', 56.0, 1)]

## Implementing Different Types of Joins for Lists

In [6]:
# Append record to the details list
details.append((4626592, 'Shorts','Protest',48.0, 1))
details

[(9423517, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, 'Socks', 'Vans', 15.0, 1),
 (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, 'Socks', 'DC', 10.0, 2),
 (9423534, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, 'Hoody', 'Animal', 44.0, 1),
 (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, 'Shorts', 'Globe', 26.0, 1),
 (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, 'Sweater', 'Dickies', 56.0, 1),
 (4626592, 'Shorts', 'Protest', 48.0, 1)]

In [7]:
# right join with 2 lists where 1 list has non matching records
# the record above is missing the order summary information so right join is appropriate
order_details_right = [[o for o in orders if d[0] in o][0] + d[1:] if d[0] in [o[0] for o
                        in orders] else (d[0], None, None) + d[1:] for d in details]
order_details_right

[(9423517, '2021-08-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1),
 (9423517, '2021-08-04', 9001, 'Jacket', 'The North Face', 112.0, 1),
 (4626232, '2021-08-04', 9003, 'Socks', 'Vans', 15.0, 1),
 (4626232, '2021-08-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1),
 (9423534, '2021-08-04', 9001, 'Socks', 'DC', 10.0, 2),
 (9423534, '2021-08-04', 9001, 'Socks', 'Quiksilver', 12.0, 2),
 (9423679, '2021-08-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1),
 (4626377, '2021-08-05', 9003, 'Hoody', 'Animal', 44.0, 1),
 (4626377, '2021-08-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1),
 (4626412, '2021-08-05', 9004, 'Shirt', 'Volcom', 78.0, 1),
 (9423783, '2021-08-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2),
 (9423783, '2021-08-06', 9002, 'Shorts', 'Globe', 26.0, 1),
 (4626490, '2021-08-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1),
 (4626490, '2021-08-06', 9004, 'Sweater', 'Dickies', 56.0, 1),
 (4626592, None, None, 'Shorts', 'Protest', 48.0, 1)]

In [8]:
# To sum up the price * quantity of the orders above
sum(pr*qt for _, _, _, _, _, pr, qt in order_details_right)

779.0

In [9]:
# To sum up only the matching records between orders and order details
sum(pr*qt for _, dt, _, _, _, pr, qt in order_details_right if dt !=None)

731.0

## Concatenating NumPy Arrays

In [10]:
import numpy as np

# Create 3 arrays
jeff_salary = [2000,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300, 2500, 2500]

# Combine the three arrays into the base_salary1 array
base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])

In [11]:
# Create 2 arrays
maya_salary = [2200,2400,2400]
john_salary = [2500,2700,2700]

# Combine the 2 arrays into the base_salary2 array
base_salary2 = np.array([maya_salary, john_salary])

In [12]:
# Concatenate the 2 base salary arrays into the base_salary array
base_salary = np.concatenate((base_salary1, base_salary2), axis=0)
base_salary

array([[2000, 3000, 3000],
       [2600, 2800, 2800],
       [2300, 2500, 2500],
       [2200, 2400, 2400],
       [2500, 2700, 2700]])

In [13]:
# Create a new array of month salary for each employee
new_month_salary = np.array([[3000],[2900],[2500],[2500],[2700]])

# Concatenate the new_month_salary into the base_salary as a new column (axis=1)
base_salary = np.concatenate((base_salary, new_month_salary), axis=1)

base_salary

array([[2000, 3000, 3000, 3000],
       [2600, 2800, 2800, 2900],
       [2300, 2500, 2500, 2500],
       [2200, 2400, 2400, 2500],
       [2500, 2700, 2700, 2700]])

## Concatenating DataFrames

In [14]:
import pandas as pd

# Create dataframe of a dictionary of employee names and the salary arrays (i.e. jeff_salary)
salary_df1 = pd.DataFrame({
    "jeff":jeff_salary,
    "nick":nick_salary,
    "tom":tom_salary
})

# Change the index (row) names to be months
salary_df1.index=['June','July','August']

salary_df1 = salary_df1.T
salary_df1

      June  July  August
jeff  2000  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500

In [15]:
# Create dataframe of a dictionary of 2 more employee names and salary arrays
salary_df2 = pd.DataFrame(
    {"maya": maya_salary,
     "john":john_salary
    }, index=['June','July','August']).T
salary_df2

      June  July  August
maya  2200  2400    2400
john  2500  2700    2700

## Concatenation Along Axis 0

In [16]:
# Concatenate the dataframes by rows
salary_df = pd.concat([salary_df1, salary_df2])
salary_df

      June  July  August
jeff  2000  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500
maya  2200  2400    2400
john  2500  2700    2700

## Concatenation Along Axis 1

In [17]:
# Create dataframe of September and October salaries
salary_df3 = pd.DataFrame(
    {'September':[3000,2800,2500,2400,2700],
     'October':[3200,3000,2700,2500,2900]},
    index=['jeff','nick','tom','maya','john'])

salary_df3

      September  October
jeff       3000     3200
nick       2800     3000
tom        2500     2700
maya       2400     2500
john       2700     2900

In [18]:
# Concatenate the 2 dataframes based on columns (axis=1)
salary_df = pd.concat([salary_df, salary_df3],axis=1)
salary_df

      June  July  August  September  October
jeff  2000  3000    3000       3000     3200
nick  2600  2800    2800       2800     3000
tom   2300  2500    2500       2500     2700
maya  2200  2400    2400       2400     2500
john  2500  2700    2700       2700     2900

## Removing Columns/Rows from a dataframe

In [19]:
# Drop the columns 'September' and 'October'
salary_df = salary_df.drop(['September','October'],axis=1)

# Drop the rows 'nick' and 'maya'
salary_df = salary_df.drop(['nick','maya'],axis=0)

salary_df

      June  July  August
jeff  2000  3000    3000
tom   2300  2500    2500
john  2500  2700    2700

## Concatenating dataframes with hierarchical index

In [20]:
# Create a mutliindex dataframe of total by the index date and region
df_date_region1 = pd.DataFrame(
    [('2022-02-04','East',97.0),
     ('2022-02-04','West',243.0),
     ('2022-02-05','East',160.0),
     ('2022-02-05','West',35.0),
     ('2022-02-06','East',110.0),
     ('2022-02-06','West',86.0)],
    columns = ['Date','Region','Total']).set_index(['Date','Region'])

df_date_region1

                   Total
Date       Region
2022-02-04 East     97.0
           West    243.0
2022-02-05 East    160.0
           West     35.0
2022-02-06 East    110.0
           West     86.0

In [21]:
# Create a mutliindex dataframe of total by the index date and region
df_date_region2 = pd.DataFrame(
    [('2022-02-04','South',114.0),
     ('2022-02-05','South',325.0),
     ('2022-02-06','South',212.0)],
    columns = ['Date','Region','Total']).set_index(['Date','Region'])

df_date_region2

                   Total
Date       Region
2022-02-04 South   114.0
2022-02-05 South   325.0
2022-02-06 South   212.0

In [22]:
# Concatenate the 2 multi-index dataframes and sort by the index level
df_date_region = pd.concat([df_date_region1, df_date_region2]).sort_index(level=['Date','Region'])

df_date_region

                   Total
Date       Region
2022-02-04 East     97.0
           South   114.0
           West    243.0
2022-02-05 East    160.0
           South   325.0
           West     35.0
2022-02-06 East    110.0
           South   212.0
           West     86.0

## Implementing  a right join

In [23]:
import pandas as pd

# Create the order and details dataframes based on 2 lists
df_orders = pd.DataFrame(orders, columns = ['OrderNo','Date','Empno'])
df_details = pd.DataFrame(details, columns = ['OrderNo','Item','Brand','Price','Quantity'])

In [24]:
# Perform a right join on the order and detail dataframes based on the OrderNo
df_orders_details_right = df_orders.merge(df_details, how='right',
                                         left_on='OrderNo', right_on='OrderNo')
df_orders_details_right

    OrderNo        Date   Empno          Item           Brand  Price  Quantity
0   9423517  2021-08-04  9001.0         Jeans        Rip Curl   87.0         1
1   9423517  2021-08-04  9001.0        Jacket  The North Face  112.0         1
2   4626232  2021-08-04  9003.0         Socks            Vans   15.0         1
3   4626232  2021-08-04  9003.0         Jeans      Quiksilver   82.0         1
4   9423534  2021-08-04  9001.0         Socks              DC   10.0         2
5   9423534  2021-08-04  9001.0         Socks      Quiksilver   12.0         2
6   9423679  2021-08-05  9002.0       T-shirt       Patagonia   35.0         1
7   4626377  2021-08-05  9003.0         Hoody          Animal   44.0         1
8   4626377  2021-08-05  9003.0  Cargo Shorts          Animal   38.0         1
9   4626412  2021-08-05  9004.0         Shirt          Volcom   78.0         1
10  9423783  2021-08-06  9002.0  Boxer Shorts        Superdry   30.0         2
11  9423783  2021-08-06  9002.0        Shorts           Globe   26.0         1
12  4626490  2021-08-06  9004.0  Cargo Shorts       Billabong   54.0         1
13  4626490  2021-08-06  9004.0       Sweater         Dickies   56.0         1
14  4626592         NaN     NaN        Shorts         Protest   48.0         1

In [25]:
# Fill any NaN values in the Empno column with a '0'
df_orders_details_right = df_orders_details_right.fillna({'Empno':0}).astype({'Empno':'int64'})
df_orders_details_right

    OrderNo        Date  Empno          Item           Brand  Price  Quantity
0   9423517  2021-08-04   9001         Jeans        Rip Curl   87.0         1
1   9423517  2021-08-04   9001        Jacket  The North Face  112.0         1
2   4626232  2021-08-04   9003         Socks            Vans   15.0         1
3   4626232  2021-08-04   9003         Jeans      Quiksilver   82.0         1
4   9423534  2021-08-04   9001         Socks              DC   10.0         2
5   9423534  2021-08-04   9001         Socks      Quiksilver   12.0         2
6   9423679  2021-08-05   9002       T-shirt       Patagonia   35.0         1
7   4626377  2021-08-05   9003         Hoody          Animal   44.0         1
8   4626377  2021-08-05   9003  Cargo Shorts          Animal   38.0         1
9   4626412  2021-08-05   9004         Shirt          Volcom   78.0         1
10  9423783  2021-08-06   9002  Boxer Shorts        Superdry   30.0         2
11  9423783  2021-08-06   9002        Shorts           Globe   26.0         1
12  4626490  2021-08-06   9004  Cargo Shorts       Billabong   54.0         1
13  4626490  2021-08-06   9004       Sweater         Dickies   56.0         1
14  4626592         NaN      0        Shorts         Protest   48.0         1

## Implementing a many-to-many join

In [26]:
# Create 2 dataframes for books and authors based on dictionaries
books = pd.DataFrame({'book_id':['b1','b2','b3'],
                      'title':['Beautiful Coding', 'Python for Web Development','Pythonic Thinking'],
                      'topic':['programming','Python, Web','Python']
                     })
authors = pd.DataFrame({'author_id':['jsn','tri','wsn'],
                        'author':['Johnson','Treloni','Willson']
                       })

In [27]:
# Create a matching dataframe to be the go between for the books and authors dataframes
matching = pd.DataFrame({'author_id':['jsn','jsn','tri','wsn'],
                         'book_id':['b1','b2','b2','b3']
                        })
matching

  author_id book_id
0       jsn      b1
1       jsn      b2
2       tri      b2
3       wsn      b3

In [28]:
# Merge the 2 dataframes together using the matching dataframe as an intermediary
authorship = books.merge(matching).merge(authors)[['title','topic','author']]
authorship

                        title        topic   author
0            Beautiful Coding  programming  Johnson
1  Python for Web Development  Python, Web  Johnson
2  Python for Web Development  Python, Web  Treloni
3           Pythonic Thinking       Python  Willson