In [1]:
from os import listdir
FileNames = listdir('Speeches')
print(FileNames)

['BattleCreekDec19_2019.txt', 'BemidjiSep18_2020.txt', 'CharlestonFeb28_2020.txt', 'CharlotteMar2_2020.txt', 'CincinnatiAug1_2019.txt', 'ColoradorSpringsFeb20_2020.txt', 'DallasOct17_2019.txt', 'DesMoinesJan30_2020.txt', 'FayettevilleSep19_2020.txt', 'FayettevilleSep9_2019.txt', 'FreelandSep10_2020.txt', 'GreenvilleJul17_2019.txt', 'HendersonSep13_2020.txt', 'HersheyDec10_2019.txt', 'LasVegasFeb21_2020.txt', 'LatrobeSep3_2020.txt', 'LexingtonNov4_2019.txt', 'MilwaukeeJan14_2020.txt', 'MindenSep12_2020.txt', 'MinneapolisOct10_2019.txt', 'MosineeSep17_2020.txt', 'NewHampshireAug15_2019.txt', 'NewHampshireAug28_2020.txt', 'NewHampshireFeb10_2020.txt', 'NewMexicoSep16_2019.txt', 'OhioSep21_2020.txt', 'PhoenixFeb19_2020.txt', 'PittsburghSep22_2020.txt', 'TexasSep23_2019.txt', 'ToledoJan9_2020.txt', 'TulsaJun20_2020.txt', 'TupeloNov1_2019.txt', 'WildwoodJan28_2020.txt', 'Winston-SalemSep8_2020.txt', 'YumaAug18_2020.txt']

In [14]:
import pandas as pd
speech_df = pd.DataFrame(index=range(len(FileNames)),
                         columns=['FileName','Content'])
print(speech_df)

   FileName Content
0       NaN     NaN
1       NaN     NaN
2       NaN     NaN
3       NaN     NaN
4       NaN     NaN
5       NaN     NaN
6       NaN     NaN
7       NaN     NaN
8       NaN     NaN
9       NaN     NaN
10      NaN     NaN
11      NaN     NaN
12      NaN     NaN
13      NaN     NaN
14      NaN     NaN
15      NaN     NaN
16      NaN     NaN
17      NaN     NaN
18      NaN     NaN
19      NaN     NaN
20      NaN     NaN
21      NaN     NaN
22      NaN     NaN
23      NaN     NaN
24      NaN     NaN
25      NaN     NaN
26      NaN     NaN
27      NaN     NaN
28      NaN     NaN
29      NaN     NaN
30      NaN     NaN
31      NaN     NaN
32      NaN     NaN
33      NaN     NaN
34      NaN     NaN

In [15]:
for i, f_name in enumerate(FileNames):
    #open the file as read only in utf-8 format
    f = open('Speeches/' + f_name, 'r', encoding='utf-8') 
    print(type(f))
    # read the lines of the file and assign it to f_content
    f_content = f.readlines()
    # close the file
    f.close()
    # assign the file name to the the FileName attribute
    speech_df.at[i, 'FileName'] = f_name
    # assign the content to the content attribute
    speech_df.at[i, 'Content'] = f_content[0]

<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>
<class '_io.TextIOWrapper'>

In [16]:
speech_df.head()

,FileName,Content
0,BattleCreekDec19_2019.txt,Thank you. Thank you. Thank you to Vice Presid...
1,BemidjiSep18_2020.txt,There's a lot of people. That's great. Thank y...
2,CharlestonFeb28_2020.txt,Thank you. Thank you. Thank you. All I can say...
3,CharlotteMar2_2020.txt,"I want to thank you very much. North Carolina,..."
4,CincinnatiAug1_2019.txt,Thank you all. Thank you very much. Thank you ...

In [18]:
air_df = pd.read_csv('TempData.csv')
air_df.head()

   Temp  Year  Month  Day      Time
0  79.0  2016      1    1  00:00:00
1  79.0  2016      1    1  00:30:00
2  79.0  2016      1    1  01:00:00
3  77.0  2016      1    1  01:30:00
4  78.0  2016      1    1  02:00:00

In [19]:
air_df['Year'].unique()

array([2016], dtype=int64)

In [20]:
air2016_df = air_df.drop(columns=['Year'])

In [22]:
air2016_df.set_index(['Month','Day','Time'], inplace=True)

In [23]:
air2016_df.head()

                    Temp
Month Day Time
1     1   00:00:00  79.0
          00:30:00  79.0
          01:00:00  79.0
          01:30:00  77.0
          02:00:00  78.0

In [26]:
# to find a record using a multi-level index search
air2016_df.loc[1,1,'00:30:00']

                    Temp
Month Day Time
1     1   00:30:00  79.0

In [28]:
response_df = pd.read_csv('OSMI Mental Health in Tech Survey 2019.csv')
response_df.head()

,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",...,Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,What country do you *work* in?,What US state or territory do you *work* in?
0,False,26-100,True,True,I don't know,No,Yes,Yes,I don't know,Very easy,...,NaN,NaN,False,25,Male,United States of America,Nebraska,White,United States of America,Nebraska
1,False,26-100,True,True,Yes,No,No,Yes,Yes,I don't know,...,NaN,NaN,False,51,male,United States of America,Nebraska,White,United States of America,Nebraska
2,False,26-100,True,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,I think opening up more conversation around th...,Thank you,True,27,Male,United States of America,Illinois,White,United States of America,Illinois
3,False,100-500,True,True,I don't know,No,Yes,Yes,Yes,Very easy,...,NaN,NaN,False,37,male,United States of America,Nebraska,White,United States of America,Nebraska
4,False,26-100,True,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,...,NaN,NaN,False,46,m,United States of America,Nebraska,White,United States of America,Nebraska

In [30]:
len(response_df)

352

In [36]:
# you can use the format function when creating a list
keys = ['Q{}'.format (i) for i in range(1, 83)]
columns_dic = pd.Series(response_df.columns, index=keys)

In [37]:
# this would be used as a translater table when the reponse_df columns names are changed
columns_dic

Q1                              *Are you self-employed?*
Q2     How many employees does your company or organi...
Q3     Is your employer primarily a tech company/orga...
Q4     Is your primary role within your company relat...
Q5     Does your employer provide mental health benef...
                             ...
Q78                       What country do you *live* in?
Q79         What US state or territory do you *live* in?
Q80                                   What is your race?
Q81                       What country do you *work* in?
Q82         What US state or territory do you *work* in?
Length: 82, dtype: object

In [39]:
# change the column names of response_df tp the keys (Q1, Q2, etc)
response_df.columns = keys

In [40]:
response_df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q73,Q74,Q75,Q76,Q77,Q78,Q79,Q80,Q81,Q82
0,False,26-100,True,True,I don't know,No,Yes,Yes,I don't know,Very easy,...,NaN,NaN,False,25,Male,United States of America,Nebraska,White,United States of America,Nebraska
1,False,26-100,True,True,Yes,No,No,Yes,Yes,I don't know,...,NaN,NaN,False,51,male,United States of America,Nebraska,White,United States of America,Nebraska
2,False,26-100,True,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,...,I think opening up more conversation around th...,Thank you,True,27,Male,United States of America,Illinois,White,United States of America,Illinois
3,False,100-500,True,True,I don't know,No,Yes,Yes,Yes,Very easy,...,NaN,NaN,False,37,male,United States of America,Nebraska,White,United States of America,Nebraska
4,False,26-100,True,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,...,NaN,NaN,False,46,m,United States of America,Nebraska,White,United States of America,Nebraska