#### Parsing HTML Text

In [1]:
example_html = """
<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor=#ffffff">
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>
"""

In [2]:
from bs4 import BeautifulSoup

In [3]:
soup = BeautifulSoup(example_html, 'html.parser')
print(soup.h1.text)

This is a Header

#### Parsing Remote HTML

In [4]:
soup = BeautifulSoup('http://hajba.hu', 'html.parser')
soup

C:\Users\timry\AppData\Local\Temp\ipykernel_26208\2587812582.py:1: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  soup = BeautifulSoup('http://hajba.hu', 'html.parser')

http://hajba.hu

In [5]:
import requests

In [6]:
# Retrieve the website
# Parse the text
# Show only the first 125 characters
soup = BeautifulSoup(requests.get('http://hajba.hu').text, 'html.parser')
soup.get_text()[:125]

'Gabor Laszlo Hajba – MediumSitemapOpen in appSign upSign inMedium LogoWriteSign upSign inGabor Laszlo Hajbahe/him63 followers'

In [7]:
# Print 2059 lines from a text file
# Changed to only print first 20 rows
# From Python_for_Data_Science pg64,67 book
r = requests.get('https://github.com/pythondatabook/sources/blob/main/ch4/excerpt.txt')
for i, line in enumerate(r.text.split('\n')[:20]): # work with only first 20 rows
    if line.strip():
        print("Line %i: " %(i), line.strip())

Line 6:  <!DOCTYPE html>
Line 7:  <html
Line 8:  lang="en"
Line 10:  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
Line 11:  data-a11y-animated-images="system" data-a11y-link-underlines="true"
Line 13:  >
Line 18:  <head>
Line 19:  <meta charset="utf-8">

#### Parsing a File

In [8]:
with open('example.txt') as infile:
    soup = BeautifulSoup(infile, 'html.parser')
    print(soup.h1.text)

This is a Header

#### Extracting All Links

In [9]:
soup = BeautifulSoup(example_html, 'html.parser')
links = soup.find_all('a', href=True) # Filters only anchors with an href attribute
for link in links:
    print(link['href']) # print only the href attribute of the anchor

http://somegreatsite.com
mailto:support@yourcompany.com

In [10]:
soup = BeautifulSoup(example_html, 'html.parser')
links = soup.find_all('a') # the href attribute filter can be removed
for link in links:
    print(link)

<a href="http://somegreatsite.com">Link Name</a>
<a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<a>This is an empty anchor</a>

In [11]:
soup = BeautifulSoup(example_html, 'html.parser')
links = soup.find_all('a', href=True) # Filters only anchors with an href attribute
for link in links:
    print(link) # print the anchors

<a href="http://somegreatsite.com">Link Name</a>
<a href="mailto:support@yourcompany.com">support@yourcompany.com</a>

#### Extracting All Images

In [12]:
soup = BeautifulSoup(example_html, 'html.parser')
images = soup.find_all('img', src=True) # Filter only the image tags with a src attribute
for image in images:
    print(image['src']) # print the src attribute text - image file name

clouds.jpg

In [13]:
soup = BeautifulSoup(example_html, 'html.parser')
images = soup.find_all('img', src=True) # Filter only the image tags with a src attribute
for image in images:
    print(image) # print the img tag text

<img align="bottom" src="clouds.jpg"/>

In [14]:
soup = BeautifulSoup(example_html, 'html.parser')
images = soup.find_all('img', src=True) # Filter only the image tags with a src attribute
for image in images:
    print(image['align']) # print the align attribute text of the img tag

bottom

#### Finding Tages Through Their Attributes

In [15]:
import re

In [16]:
soup = BeautifulSoup(example_html, 'html.parser')
print(soup.find('p', id='first'))
print(soup.find_all('p', class_='paragraph'))
print(soup.find('img', src='clouds.jpg'))
print(soup.find('img', src=re.compile(r'\.gif$')))
print(soup.find('img', src=re.compile(r'\.jpg$')))
print(soup.find('img', src=re.compile(r'\.png$')))
print(soup.find_all('p', string='paragraph')) # use 'string' instead of 'text'
print(soup.find_all('p', string=re.compile('paragraph'))) # search for 'paragraph' within the text of a paragraph

None
[]
<img align="bottom" src="clouds.jpg"/>
None
<img align="bottom" src="clouds.jpg"/>
None
[]
[<p>This is a paragraph!</p>]

In [17]:
soup = BeautifulSoup(requests.get('http://hajba.hu').text, 'html.parser')
print(soup.find('p', id='first'))
print(soup.find_all('p', class_='paragraph'))
print(soup.find('img', src='clouds.jpg'))
print(soup.find('img', src=re.compile(r'\.gif$')))
print(soup.find('img', src=re.compile(r'\.jpg$')))
print(soup.find('img', src=re.compile(r'\.png$')))
print(soup.find_all('p', string='paragraph')) # use 'string' instead of 'text'
print(soup.find_all('p', string=re.compile('paragraph'))) # search for 'paragraph' within the text of a paragraph

None
[]
None
None
None
<img alt="" class="m dj bx by bz fn" height="32" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fill:64:64/1*dmbNkD5D-u45r44go_cf0g.png" width="32"/>
[]
[]

In [18]:
soup = BeautifulSoup(requests.get('https://github.com/pythondatabook/sources/blob/main/ch4/excerpt.txt').text, 'html.parser')
print(soup.find('p', id='first'))
print(soup.find_all('p', class_='paragraph'))
print(soup.find('img', src='clouds.jpg'))
print(soup.find('img', src=re.compile(r'\.gif$')))
print(soup.find('img', src=re.compile(r'\.jpg$')))
print(soup.find('img', src=re.compile(r'\.png$')))
print(soup.find_all('p', string='paragraph')) # use 'string' instead of 'text'
print(soup.find_all('p', string=re.compile('paragraph'))) # search for 'paragraph' within the text of a paragraph

None
[]
None
None
None
None
[]
[]

#### Finding Multiple Tags Based on Property

In [19]:
tags = []
#unique_tags = []
soup = BeautifulSoup(example_html, 'html.parser')
for tag in soup.find_all(re.compile('h')): # find all tags that contain the letter 'h'
    tags.append(tag.name)
unique_list = tags
unique_list = list(set(unique_list))
print(unique_list)

['h1', 'html', 'hr', 'head', 'h2']

In [20]:
tags = []
soup = BeautifulSoup(requests.get('http://hajba.hu').text, 'html.parser')
for tag in soup.find_all(re.compile('h')): # find all tags that contain the letter 'h'
    tags.append(tag.name)
unique_list = tags
unique_list = list(set(unique_list))
print(unique_list)

['h3', 'html', 'head', 'path', 'h2']

In [21]:
tags = []
soup = BeautifulSoup(requests.get('https://github.com/pythondatabook/sources/blob/main/ch4/excerpt.txt').text, 'html.parser')
for tag in soup.find_all(re.compile('h')): # find all tags that contain the letter 'h'
    tags.append(tag.name)
unique_list = tags
unique_list = list(set(unique_list))
print(unique_list)

['h1', 'anchored-position', 'h3', 'header', 'ghcc-consent', 'qbsearch-input', 'auto-check', 'html', 'react-partial-anchor', 'head', 'path', 'h2', 'dialog-helper']

#### Changing Content

#### Adding Tags and Attributes

In [22]:
soup = BeautifulSoup(example_html, 'html.parser')
soup

<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>

In [23]:
soup = BeautifulSoup(example_html, 'html.parser')
h2 = soup.new_tag('h2')
h2.string = 'This is a second-level header'
soup.insert(0,h2) # insert the h2 tag at the 0 level
soup

<h2>This is a second-level header</h2>
<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>

In [24]:
soup.insert(1,h2) # inserts after the </h1> end tag
soup

<h2>This is a second-level header</h2>
<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>

In [25]:
soup.append(soup.new_tag('p')) # inserts <p></p> after the </html>
soup

<h2>This is a second-level header</h2>
<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>
<p></p>

In [26]:
soup.head['style'] = 'bold' # add the bold style to the <head> tag
soup

<h2>This is a second-level header</h2>
<html>
<head style="bold">
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p>This is a paragraph!</p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>
<p></p>

#### Changing Tags and Attributes

In [27]:
soup = BeautifulSoup(example_html, 'html.parser')

# Cycle through the soup object searching for <p> tags
for p in soup.find_all('p', string = True):
    p.string.wrap(soup.new_tag('b'))
soup

<html>
<head>
<title>Your Title Here</title>
</head>
<body bgcolor='#ffffff"'>
<center>
<img align="bottom" src="clouds.jpg"/>
</center>
<hr/>
<a href="http://somegreatsite.com">Link Name</a> is a link to another nifty site
<h1>This is a Header</h1>
<h2>This is a Medium Header</h2>
Send me email at <a href="mailto:support@yourcompany.com">support@yourcompany.com</a>
<p><b>This is a paragraph!</b></p>
<p>
<b>This is a new paragraph!</b><br/>
<b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>
<a>This is an empty anchor</a>
</p>
<hr/>
</body>
</html>

In [28]:
soup = BeautifulSoup('<p> This is a <b>new</b> paragraph!</p>')
p = soup.p.b.unwrap() # removes (unwraps) the bold <b> attribute tag
print(soup.p)

<p> This is a new paragraph!</p>

#### Deleting Tags and Attributes

In [29]:
soup = BeautifulSoup(example_html, 'html.parser')
print(soup.title.extract()) # removes the tag and returns it so you can use it elsewhere
print(soup.head)

<title>Your Title Here</title>
<head>

</head>

In [30]:
soup = BeautifulSoup(example_html, 'html.parser')
print(soup.title.decompose()) # permanebtly deletes the tag
print(soup.head)

None
<head>

</head>

In [31]:
soup = BeautifulSoup(example_html, 'html.parser')

print(len(soup.find_all(True, display=True)))

# delete the display attribute from tags
for tag in soup.find_all(True, display=True):
    del tag['display']

print(len(soup.find_all(True, display=True)))

0
0

#### Finding Comments

In [32]:
from bs4 import Comment

In [33]:
soup = BeautifulSoup(example_html, 'html.parser')
for comment in soup.find_all(string=lambda string:isinstance(string, Comment)):
    print(comment)

In [34]:
soup = BeautifulSoup(requests.get('http://hajba.hu').text, 'html.parser')
for comment in soup.find_all(string=lambda string:isinstance(string, Comment)):
    print(comment)

In [35]:
soup = BeautifulSoup(requests.get('https://github.com/pythondatabook/sources/blob/main/ch4/excerpt.txt').text, 'html.parser')
for comment in soup.find_all(string=lambda string:isinstance(string, Comment)):
    print(comment)

 '"`
 </textarea></xmp>
 '"`
 </textarea></xmp>
 '"`
 </textarea></xmp>

#### Converting a Soup to HTML Text

In [36]:
print(soup.find('p').prettify())

<p>
 We read every piece of feedback, and take your input very seriously.
</p>

#### Extracting Data

In [43]:
url = 'https://www.sainsburys.co.uk/robots.txt'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')
soup

<html><head>
<title>Access Denied</title>
</head><body>
<h1>Access Denied</h1>

You don't have permission to access "http://www.sainsburys.co.uk/robots.txt" on this server.<p>
Reference #18.d325c017.1754592619.3d9e7257
<p>https://errors.edgesuite.net/18.d325c017.1754592619.3d9e7257</p>
</p></body>
</html>

In [44]:
url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

In [45]:
# Use this to get the url netloc
from urllib.parse import urlparse
host = urlparse(url).netloc
scheme = urlparse(url).scheme
print(host)
print(scheme)

www.vons.com
https

In [46]:
# display all html code that is related to embedded javascripts
#soup.find_all('script')

In [47]:
# Find anchors with 'Salmon' in the text
#.find_all('a', string=re.compile(r'Sockeye'))

In [48]:
# Find anchors with 'Salmon' in the text
#soup.find_all('a', string=re.compile(r'Salmon'))

In [49]:
# Get href links of products in the fish and seafood department
url_links = []
fish_links = soup.find_all('a', class_='product-title__name')
if fish_links:
    for fish_link in fish_links:
        href = fish_link.get("href")
        if href:
            url_links.append(scheme+'://'+host+href)
url_links

['https://www.vons.com/shop/product-details.186190050.html',
 'https://www.vons.com/shop/product-details.186190041.html',
 'https://www.vons.com/shop/product-details.960035112.html',
 'https://www.vons.com/shop/product-details.960116488.html',
 'https://www.vons.com/shop/product-details.960264310.html',
 'https://www.vons.com/shop/product-details.960122401.html',
 'https://www.vons.com/shop/product-details.960569306.html',
 'https://www.vons.com/shop/product-details.960227381.html',
 'https://www.vons.com/shop/product-details.960137751.html',
 'https://www.vons.com/shop/product-details.960190258.html',
 'https://www.vons.com/shop/product-details.960119273.html',
 'https://www.vons.com/shop/product-details.960089210.html',
 'https://www.vons.com/shop/product-details.960035113.html',
 'https://www.vons.com/shop/product-details.960089211.html',
 'https://www.vons.com/shop/product-details.186190017.html',
 'https://www.vons.com/shop/product-details.970066113.html',
 'https://www.vons.com/shop/product-details.970536666.html',
 'https://www.vons.com/shop/product-details.960091091.html',
 'https://www.vons.com/shop/product-details.186210091.html',
 'https://www.vons.com/shop/product-details.960035603.html',
 'https://www.vons.com/shop/product-details.186350057.html',
 'https://www.vons.com/shop/product-details.970001929.html',
 'https://www.vons.com/shop/product-details.960267460.html']

In [50]:
# Get the product id values in the fish and seafood department
product_id_links = []
fish_links = soup.find_all('a', class_='product-title__name')
if fish_links:
    for fish_link in fish_links:
        prod_id = fish_link.get("id")
        #prod_text = fish_link.get_text()
        if href:
            product_id_links.append(prod_id)
product_id_links[:5]

['pg186190050', 'pg186190041', 'pg960035112', 'pg960116488', 'pg960264310']

In [51]:
# Get the product description in the fish and seafood department
descr_links = []
fish_links = soup.find_all('a', class_='product-title__name')
if fish_links:
    for fish_link in fish_links:
        #prod_id = fish_link.get("id")
        prod_text = fish_link.get_text()
        if href:
            descr_links.append(prod_text)
descr_links[:5]

['Fresh Farm Raised Atlantic Salmon Fillet Color Added Value Pack - 2 lb\n                                    ',
 'Fresh Farmed Atlantic Salmon Fillet Color Added  - 1.5 lb\n                                    ',
 'waterfront BISTRO Boneless Skin On Wild Alaskan Pink Salmon Fillets - 32 Oz\n                                    ',
 'waterfront BISTRO Boneless Skinless Wild Alaskan Cod Fillets - 32 Oz\n                                    ',
 'waterfront BISTRO Tilapia Fillets Bonesless & Skinless - 16 Oz\n                                    ']

In [52]:
# Cannot retrieve product details of an item
# Website protected by Icapsula
#url = url_links[3]
#print(url)
#print(requests.get(url).content)
#soup = BeautifulSoup(requests.get(url).status_code, 'html.parser')
#soup

In [53]:
# Cannot run. Site protected by Incapsula
url = url_links[3]
#soup = BeautifulSoup(requests.get(url).text, 'html.parser')
#table = soup.find('table', class_='nutrition-panel__table')
#if table:
#    rows = table.findall('tr', class_='nutrition-panel__table__row')
#    for tr in rows:
#        print(tr)

#### Using Dictionaries to Save Data

In [55]:
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import requests

url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

product={}
products={}

# Use this to get the url netloc
host = urlparse(url).netloc
scheme = urlparse(url).scheme
print(host)
print(scheme)

# Get href links of products in the fish and seafood department
fish_links = soup.find_all('a', class_='product-title__name')
if fish_links:
    for fish_link in fish_links:
        href = fish_link.get("href")
        if href:
            # Add the url to the dictionary
            url = scheme+'://'+host+href
            product = {'url':url}

            # Add the product_id to the dictionary
            prod_id = fish_link.get("id")
            product['product_id'] = prod_id

            # Add the description tot he dictionary
            prod_text = fish_link.get_text()
            product['desc'] = prod_text.strip
        products
product

www.vons.com
https

{'url': 'https://www.vons.com/shop/product-details.960267460.html',
 'product_id': 'pg960267460',
 'desc': <function str.strip(chars=None, /)>}

In [56]:
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import requests

url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

product={}

# Use this to get the url netloc
host = urlparse(url).netloc
scheme = urlparse(url).scheme
#print(host)
#print(scheme)

# Get href links of products in the fish and seafood department
fish_links = soup.find_all('a', class_='product-title__name')

if fish_links:
    for i, fish_link in enumerate(fish_links[:5]): # only run for the first 5 rows
        #print(fish_link)
        href = fish_link.get("href")
        if href:
            # Add the url to the dictionary
            #key_id = 'url'+str(x)
            url = scheme+'://'+host+href
            product[i] = [url]

            # Add the product_id to the dictionary
            prod_id = fish_link.get("id")
            product[i].append(prod_id)

            # Add the description to the dictionary
            prod_text = fish_link.get_text()
            product[i].append(prod_text.strip())

# Show the 5 products retrieved from the website in dictionary form
for key, value in product.items():
    print(key, value)

0 ['https://www.vons.com/shop/product-details.186190050.html', 'pg186190050', 'Fresh Farm Raised Atlantic Salmon Fillet Color Added Value Pack - 2 lb']
1 ['https://www.vons.com/shop/product-details.186190041.html', 'pg186190041', 'Fresh Farmed Atlantic Salmon Fillet Color Added  - 1.5 lb']
2 ['https://www.vons.com/shop/product-details.960035112.html', 'pg960035112', 'waterfront BISTRO Boneless Skin On Wild Alaskan Pink Salmon Fillets - 32 Oz']
3 ['https://www.vons.com/shop/product-details.960116488.html', 'pg960116488', 'waterfront BISTRO Boneless Skinless Wild Alaskan Cod Fillets - 32 Oz']
4 ['https://www.vons.com/shop/product-details.960264310.html', 'pg960264310', 'waterfront BISTRO Tilapia Fillets Bonesless & Skinless - 16 Oz']

In [57]:
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

products=pd.DataFrame(columns=['Product_id', 'Url', 'Description'])

# Use this to get the url netloc
host = urlparse(url).netloc
scheme = urlparse(url).scheme
#print(host)
#print(scheme)

# Get href links of products in the fish and seafood department
fish_links = soup.find_all('a', class_='product-title__name')

if fish_links:
    for i, fish_link in enumerate(fish_links[:5]): # only run for the first 5 rows
        #print(fish_link)
        href = fish_link.get("href")
        if href:
            # Add the url to the dictionary
            url = scheme+'://'+host+href
        
            # Add the product_id to the dictionary
            prod_id = fish_link.get("id")
            #product[i].append(prod_id)

            # Add the description to the dictionary
            prod_text = fish_link.get_text()
            #product[i].append(prod_text.strip())

            # Insert new row into the products dataframe
            products.loc[len(products)]= [prod_id,
                                         url,
                                         prod_text]

# Show the 5 products retrieved from the website in dataframe form
products

,Product_id,Url,Description
0,pg186190050,https://www.vons.com/shop/product-details.1861...,Fresh Farm Raised Atlantic Salmon Fillet Color...
1,pg186190041,https://www.vons.com/shop/product-details.1861...,Fresh Farmed Atlantic Salmon Fillet Color Adde...
2,pg960035112,https://www.vons.com/shop/product-details.9600...,waterfront BISTRO Boneless Skin On Wild Alaska...
3,pg960116488,https://www.vons.com/shop/product-details.9601...,waterfront BISTRO Boneless Skinless Wild Alask...
4,pg960264310,https://www.vons.com/shop/product-details.9602...,waterfront BISTRO Tilapia Fillets Bonesless & ...

In [58]:
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

df_products=pd.DataFrame(columns=['Product_id', 'Url', 'Description'])

# Use this to get the url netloc
host = urlparse(url).netloc
scheme = urlparse(url).scheme

# Get href links of products in the fish and seafood department
fish_links = soup.find_all('a', class_='product-title__name')

if fish_links:
    for i, fish_link in enumerate(fish_links[:10]): # only run for the first 5 rows

        # Add the url to the list
        href = fish_link.get("href")
        if href:
            url = scheme+'://'+host+href
        else: url = None

        # Add the product_id to the list
        prod_id = fish_link.get("id")
        if not prod_id:
            prod_id = None   

        # Add the description to the list
        prod_text = fish_link.get_text()
        if not prod_text:
            prod_text = None

        # Insert new row into the products dataframe
        df_products.loc[len(df_products)]= [prod_id,
                                      url,
                                      prod_text]

# Show the 10 products retrieved from the website in dataframe form
df_products

,Product_id,Url,Description
0,pg186190050,https://www.vons.com/shop/product-details.1861...,Fresh Farm Raised Atlantic Salmon Fillet Color...
1,pg186190041,https://www.vons.com/shop/product-details.1861...,Fresh Farmed Atlantic Salmon Fillet Color Adde...
2,pg960035112,https://www.vons.com/shop/product-details.9600...,waterfront BISTRO Boneless Skin On Wild Alaska...
3,pg960116488,https://www.vons.com/shop/product-details.9601...,waterfront BISTRO Boneless Skinless Wild Alask...
4,pg960264310,https://www.vons.com/shop/product-details.9602...,waterfront BISTRO Tilapia Fillets Bonesless & ...
5,pg960122401,https://www.vons.com/shop/product-details.9601...,Open Nature Skin On Wild Caught Alaskan Sockey...
6,pg960569306,https://www.vons.com/shop/product-details.9605...,Waterfront Bistro Catfish Fillets - 16 Oz\n ...
7,pg960227381,https://www.vons.com/shop/product-details.9602...,waterfront BISTRO Boneless Skinless Wild Alask...
8,pg960137751,https://www.vons.com/shop/product-details.9601...,Fresh Atlantic Salmon Color Added Portion 1 ct...
9,pg960190258,https://www.vons.com/shop/product-details.9601...,waterfront BISTRO Boneless Skin On Wild Alaska...

### Exporting Data

#### To CSV

In [59]:
import csv

#### Line Endings

In [60]:
with open('result.csv','w') as outfile:
    spamwriter = csv.writer(outfile)
    # the hidden endline '\r\n' will cause an added empty row in excel
    # it won't do that in notepad or jupyter
    spamwriter.writerow([1,2,3,4,5]) 
    spamwriter.writerow([6,7,8,9,0])

In [61]:
with open('result2.csv','w') as outfile:
    # The lineterminator changes the end value to '\n' as a newline return
    spamwriter = csv.writer(outfile, lineterminator='\n')
    spamwriter.writerow([1,2,3,4,5])
    spamwriter.writerow([6,7,8,9,0])
    spamwriter.writerow([1,2,3,4,5])

#### Headers

In [62]:
with open('result3.csv','w') as outfile:
    spamwriter = csv.writer(outfile, lineterminator='\n')
    # write headers into the first row
    spamwriter.writerow(['average','mean','median','max','sum'])
    spamwriter.writerow([1,2,3,4,5])
    spamwriter.writerow([6,7,8,9,0])

In [63]:
column_names = ['average','mean','median','max','sum']
df = pd.read_csv('result2.csv', header=None, names=column_names)
df.to_csv('results2_updated.csv', index=False)

#### Saving a Dictionary

In [64]:
column_names = ['average','mean','median','max','sum']

with open('result4.csv','w', newline='') as outfile:
    spamwriter = csv.DictWriter(outfile, fieldnames = column_names)
    spamwriter.writeheader()
    spamwriter.writerow({'average': 1,
                         'mean': 2,
                         'median': 3,
                         'max': 4,
                         'sum': 5})

In [65]:
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import requests

url = 'https://www.vons.com/shop/aisles/meat-seafood/fish-shellfish/fish.html?sort=&page=1&loc=2053'
soup = BeautifulSoup(requests.get(url).text, 'html.parser')

product={}

# Use this to get the url netloc
host = urlparse(url).netloc
scheme = urlparse(url).scheme

# Get href links of products in the fish and seafood department
fish_links = soup.find_all('a', class_='product-title__name')

if fish_links:
    for i, fish_link in enumerate(fish_links[:5]): # only run for the first 5 rows
        #print(fish_link)
        href = fish_link.get("href")
        if href:
            # Add the url to the dictionary
            #key_id = 'url'+str(x)
            url = scheme+'://'+host+href
            product[i] = [url]

            # Add the product_id to the dictionary
            prod_id = fish_link.get("id")
            product[i].append(prod_id)

            # Add the description to the dictionary
            prod_text = fish_link.get_text()
            product[i].append(prod_text.strip())

# Show the 5 products retrieved from the website in dictionary form
for key, value in product.items():
    print(value)

['https://www.vons.com/shop/product-details.186190050.html', 'pg186190050', 'Fresh Farm Raised Atlantic Salmon Fillet Color Added Value Pack - 2 lb']
['https://www.vons.com/shop/product-details.186190041.html', 'pg186190041', 'Fresh Farmed Atlantic Salmon Fillet Color Added  - 1.5 lb']
['https://www.vons.com/shop/product-details.960035112.html', 'pg960035112', 'waterfront BISTRO Boneless Skin On Wild Alaskan Pink Salmon Fillets - 32 Oz']
['https://www.vons.com/shop/product-details.960116488.html', 'pg960116488', 'waterfront BISTRO Boneless Skinless Wild Alaskan Cod Fillets - 32 Oz']
['https://www.vons.com/shop/product-details.960264310.html', 'pg960264310', 'waterfront BISTRO Tilapia Fillets Bonesless & Skinless - 16 Oz']

In [66]:
# Write products from www.vons.com into a csv file
column_names = ['URL','Product_Id', 'Description']
with open('vons.csv','w') as outfile:
    spamwriter = csv.writer(outfile, lineterminator='\n')
    spamwriter.writerow(column_names)
    for dict_value in product.values():
        spamwriter.writerow(dict_value)

#### To JSON

In [67]:
import json

In [68]:
with open('result.json','w') as outfile:
    json.dump([{'average':12, 'median':11},
               {'average':10, 'median':10}], outfile)

In [69]:
with open('result2.json','w') as outfile:
    json.dump([{'xaverage':12, 'median':11},
               {'xaverage':10, 'median':10},
               {'xaverage':11, 'median':11}
              ],
              # sort_keys will sort by the key names (xaverage, median)
              outfile, sort_keys=True)

#### Saving a Dictionary

In [70]:
with open('vons.json','w') as outfile:
    json.dump(product, outfile)

#### To a Relational Database

In [71]:
import sqlite3

In [72]:
table_ddl = """
CREATE TABLE IF NOT EXISTS vons(
    product_id TEXT PRIMARY KEY,
    url TEXT,
    description TEXT
)
"""

sqlite_insert = """
INSERT OR REPLACE INTO vons
    values(?, ?, ?)
"""

In [113]:
def save_to_sqlite(database_path, dataframe):
    global connection
    connection = __connect(database_path)

    # Check to verify db connection
    if not connection: return

    # Check to verify table exists
    try: 
        __ensure_table(connection)
    except sqlite3.Error as e:
        print(f"SQLite error: {e}")
        __close_connection()
        
    # Save data to table
    try:
        for row in range(len(dataframe)):
            __save_row(row, dataframe)
    except sqlite3.Error as e:
        print(f"SQLite error: {e}")
        __close_connection()
    
    __close_connection()

def __connect(database):
    try:
        conn = sqlite3.connect(database)
        cursor = conn.cursor()
        # Attempt simple query to verify connection
        cursor.execute("SELECT 1")
        print(f'Database connection established')
        return sqlite3.connect(database)
    except sqlite3.Error as e:
        print(f'Database connection error: {e}')
        return False
    

def __close_connection():
    
    if connection:
        connection.close()
        print(f'Database connection is closed')

def __ensure_table(conn):

    cursor = conn.cursor()
    cursor.execute(f"SELECT Product_id FROM vons LIMIT 1")
    result = cursor.fetchone()
    if not result:
        print(f'Creating Vons table')
        connection.execute(table_ddl)
    else: print(f'Table already exists')
    
def __save_row(row, dataframe):
    connection.execute(sqlite_insert, (
        dataframe.iloc[row]['Product_id'],
        dataframe.iloc[row]['Url'],
        dataframe.iloc[row]['Description']))
    connection.commit()
    print(f'Row {row+1} has been saved')

In [114]:
# Run the sql to save records to a table
# Create table if it doesn't exist
save_to_sqlite('my_database.db', df_products)

Database connection established
Table already exists
Row 1 has been saved
Row 2 has been saved
Row 3 has been saved
Row 4 has been saved
Row 5 has been saved
Row 6 has been saved
Row 7 has been saved
Row 8 has been saved
Row 9 has been saved
Row 10 has been saved
Database connection is closed